apiVersion: v1
data:
  MYSQL_PASSWORD: hooker111
  MYSQL_ROOT_PASSWORD: hooker111
  MYSQL_USER: manuel
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress-env
  name: wordpress-env
